### ISSUE TITLE
New release for pre-columbian and input changes

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/tr-55#39]
MMW will need an updated version for its dependency on TR55.  Check that the changes from release 0.1.0 are eventually merged into `master` - the changelog and setup.py changes seem to have not been applied.

https://github.com/WikiWatershed/tr-55/commit/71ddc67535d9f7b8c3c4b6146613112d241c9c01

**Comment by jamesmcclain** [comment]
* https://github.com/WikiWatershed/tr-55/pull/30 The output format was changed.  Previously, only the overall result of the calculation was given, after this change the overall result plus the sub-results for each (nlcd,soil) pair are given.
   * https://github.com/WikiWatershed/tr-55/pull/31 and https://github.com/WikiWatershed/tr-55/pull/38 Some code was added to generate and compare mini-app ables.  
   * https://github.com/WikiWatershed/tr-55/pull/32 Attempt to plug in the correct NLCD codes.  If I recall, previously there were some "names" in the mini-app that did not have an associated NLCD code in the TR-55.
   * https://github.com/WikiWatershed/tr-55/pull/35  This changed the the format of the input expected by the code.  It allows for areas that are covered by both reclassifications and BMPs.
   * https://github.com/WikiWatershed/tr-55/pull/37  This made it easier to do Pre-Columbian calculations.

**Comment by caseypt** [comment]
Released by @hectcastro https://github.com/WikiWatershed/tr-55/releases/tag/0.2.0
