### ISSUE TITLE
Describe behavior for Developed areas ~5cm of precipitation

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/tr-55#52]
A note from @SRGDamia1 

> In the micro-site storm model, the results for all developed land
types give have a sudden increase in infiltration at ~5cm rain with no
increase in runoff.  Logically this doesn't make sense.

We should investigate what aspect of the model is creating this behavior.  Since it occurs around 5cm, my initial guess is that it is the transition between using Pitts and TR55 - we should still be able to describe the difference between the two that would make this result, if it ends up being the case.

**Comment by jamesmcclain** [comment]
1 inch = 2.54 cm.  There is indeed a discontinuity at 2 inches when the model changes.

**Comment by SRGDamia1** [comment]
In the same vein, on developed land types at less than ~5cm rain changing the soil type yields no change in the results.  I assume this is because the Pitts model is independent of soil type.

**Comment by SRGDamia1** [comment]
This should be fixed with pull request #66
