### ISSUE TITLE
Incorrect Curve Numbers for Barren Land

### ISSUE THREAD

**Issue by SRGDamia1** [WikiWatershed/tr-55#54]
The curve numbers for barren_land in tables.py do not match with those from table C of the model brief (https://drive.google.com/open?id=0B3v0QxIOuR_nbVphWVkwTGhCOW8) or published TR55 (http://www.nrcs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb1044171.pdf)

Current numbers:
    'barren_land':          {'nlcd': 31, 'ki': 0.0, 'cn': {'a': 77, 'b': 86, 'c': **86**, 'd': **91**}},  # noqa
Correct numbers:
    'barren_land':          {'nlcd': 31, 'ki': 0.0, 'cn': {'a': 77, 'b': 86, 'c': **91**, 'd': **94**}},  # noqa

I think this should just be a super-easy change to that line in tables.py.

The other curve numbers in tables.py do match up with the model brief.

**Comment by mmcfarland** [comment]
Good catch.  We'll look at the v1 code that we ported to see if there's any explanation of the discrepancy or if it was a transcription error.
