### ISSUE TITLE
Take Conservation Practices out of pixel calculation

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/tr-55#59]
Rain Garden, Veg Basin, Green Roof & Porous Paving should not be added as a BMP in the current model implementation.  Instead, the sum of the area grouped by each type should be multiplied by a loading factor and then taken from runoff into the infiltration amount.  Land use and the other BMPs should remain as they are now.

Ex:

* 5 Rain Gardens at 10sqm each and 2 Veg Basins at 10sqm and 20sqm are added to the AoI.
* Model is run but Rain/Veg are not accounted for in cell calculations.
* 10*5*[loading factor] should be removed from runoff after all calculations are made
* (10+20)*[loading factor] should be removed from runoff after all calculations are made

**Comment by mmcfarland** [comment]
Blocked awaiting feedback on the units of the result of multiplying the "reduction factor" by the bmp area.  If it's a volume or a height measure will determine how this is implemented.

**Comment by jamesmcclain** [comment]
I just realized that it does not matter whether the "reduction factor" is for a height or a volume.

If the runoff amount is more than one factor of a quantity (e.g. runoff * runoff * 42) then it matters because there is a difference between reducing to 80% of the original amount and reducing to .8 * .8 = 64% of the original amount.  However, if runoff is only one factor of the final quantity, then reducing runoff to 80% of original will reduce both the height value and the volume value to 80% of original (that is, there is no difference between reducing the water height and the water volume).

**Comment by mmcfarland** [comment]
True - if the factor produces a percentage decrease, it should matter.  I think having a percentage decrease is a reasonable assumption (as opposed to a non-volume unit like "cm").

**Comment by mmcfarland** [comment]
> Highest on our priority is to implement the new approach to the following four small scale BMPs (rain garden, veg basin, porous pavement and green roof) that would allow them to give more accurate results AND function at sub-pixel scales. We realize that you're waiting for us on our final input on this, so we've been working hard to get you the final numbers.  See our notes from yesterday in our 2014-16-ModelMyWatershed2_TechNotes-Cumulative Google Doc and our calculations in the BMP-storage tab in Land Use Parameter Documentation Google Sheet. The general approach requires subtraction of water volumes. 

    [Current AOI runoff in volume units (m3)] = [Current AOI runoff in depth units (m)] x  [AOI area (m2)]
    [BMP storage (runoff reduction) in volume units (m3)] = [BMP area (m2)] x [Available volume for water storage per unit BMP area (m3/m2)]
    [Adjusted AOI runoff volume (m3)] = [Current AOI runoff in volume units (m3)] x [BMP storage (runoff reduction) in volume units (m3)]
        with no negative numbers allowed
    [Adjusted AOI runoff depth (m)] = [Adjusted AOI runoff volume (m3)] / [AOI area (m2)]

> The key bit of information that you need from us are the values for the [Available volume for water storage per unit BMP area (m3/m2)], which have in column H in the totals rows (in green) in the [BMP-storage tab in Land Use Parameter Documentation Google Sheet](https://docs.google.com/spreadsheets/d/1qgWUKtEFWxdRfmwo1_RCUj7-OzzIU86CaZbA54sNFR0/edit#gid=1205327723)

**Comment by mmcfarland** [comment]
For context, Stroud took the following notes when coming up with their values:
https://docs.google.com/document/d/1mG6m6wxxJjoSxK4SyYrNRaUTHZujSHYz5B7aXmCJWsQ/edit#bookmark=kix.y8rhccetti5g

**Comment by jamesmcclain** [comment]
Based on my current understanding, what I wrote above is incorrect.
